### ISSUE TITLE
Sunday as a business hours not highlighted in right color. Also issue with time stamp settings

### ISSUE THREAD

**Issue by leokady** [Servoy/fullcalendarcomponent#5]
1. I setup my business hours from Sunday to Wednesday , but Sunday always not included(color on the week view show me that is out of my business hours.). 
![image](https://user-images.githubusercontent.com/31049550/35358894-2f2ea1c2-0126-11e8-81cb-f61a827e6dbe.png)

Property set like this:   businessHours: {
			start:  '08:00:00',
			end:  '18:00:00',
			dow: [1,2,3,7]
		},
2.  I don't know if this issue or I cannot find a property. On the week view I want to set time range in 24 hours stamp, but calendar always show me from 00 --11am and 12 pm -11pm. Is it because a time zone? Is it possible to have configurable property for it.

**Comment by paronne** [comment]
Hi,

yes all the properties you are looking for are configurable in the fullcalendar.
1. the week is 0-based where 0 is Sunday, therefore you should reference to Sunday as 0 instead of 7 in your business hours object.
2. you can use the property slotLabelFormat : "H(:mm)" to format the label in the agenda timeslots.

You can reference to the fullcalendar docs (version 2) to know more about the configuration options of the fullcalendar https://fullcalendar.io/docs/

Regards,
Paolo
